In [2]:
import numpy as np

In [51]:
n=2000

In [52]:
CF_1_mu=100
CF_1_sigma=10
CF_2_mu=100
CF_2_sigma=10
CF1=numpy.random.normal(CF_1_mu, CF_2_sigma, n)
print(CF1[:5])

[110.83760588 113.80621086  80.79748874  94.53705098  95.76546918]


In [53]:
df=5
IR_r=0.02
IR_mu=0.03
IR_sigma=0.01
EQ_mu=0.03
EQ_sigma=0.02
Czynnik_IR_1=IR_mu + np.random.standard_t(df,n)*IR_sigma
Czynnik_EQ_1=EQ_mu + np.random.standard_t(df,n)*EQ_sigma
print(Czynnik_EQ_1[:5])

[ 0.03034054 -0.01188374  0.02937446  0.02885923  0.02619708]


Liczymy wartość obecną CF z punktu widzenia momentu 0

In [54]:
PV_CF=CF_1_mu / (1+IR_r) + CF_2_mu / (1+IR_r)**2
print(PV_CF)

194.15609381007306


Wartość CF z punktu widzenia momentu 1

In [55]:
PV_CF_t1=CF1 + CF_2_mu/(1+IR_r)
print(PV_CF_t1[:5])

[208.87682157 211.84542655 178.83670443 192.57626666 193.80468487]


In [56]:
Strata_L_t1=PV_CF - PV_CF_t1
Strata_L_t1[:5]

array([-14.72072776, -17.68933274,  15.31938938,   1.57982715,
         0.35140894])

In [57]:
EQ_t0=200
EQ_t1=EQ_t0*(1+Czynnik_EQ_1)
print(EQ_t1[:5])

[206.0681071  197.62325195 205.87489247 205.77184668 205.23941618]


In [58]:
Strata_A =  EQ_t1- EQ_t0
print(Strata_A[:5])

[ 6.0681071  -2.37674805  5.87489247  5.77184668  5.23941618]


In [59]:
Strata=Strata_L_t1 + Strata_A
print(Strata[:5])

[ -8.65262066 -20.06608079  21.19428185   7.35167383   5.59082513]


In [60]:
np.mean(Strata)


2.2740694584249144

In [61]:
np.mean(Strata_A)

5.954247099127424

In [63]:
np.quantile(Strata_L,0.75)

AttributeError: module 'numpy' has no attribute 'quantile'